
Vagrant.configure(2) do |config|

  config.vm.box = "rudolfochrist/ubuntu-desktop"
  config.vm.provision :shell, inline: 'wget --no-check-certificate https://github.com/aglover/ubuntu-equip/raw/master/equip_java7_64.sh && bash equip_java7_64.sh'
  
  
   config.vm.provider "virtualbox" do |vb|
  
     vb.gui = true
	 end  
 
 config.vm.provision "shell", inline: <<-SHELL
     #Installing Java version 1.8 
     sudo add-apt-repository ppa:openjdk-r/ppa
     sudo apt-get update 
     sudo apt-get install -y openjdk-8-jdk

     #Installs Eclipse Mars
     sudo wget -nv "http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/mars/1/eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz&r=1" -O eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz

     #Used for extracting the Eclipse tar file
     cd /opt/ && sudo tar -zxvf /home/vagrant/eclipse-jee-mars-1-linux-gtk-x86_64.tar.gz

    #Installs the Checker Framework Plugin   
     cd /opt/eclipse
     ./eclipse -application org.eclipse.equinox.p2.director -noSplash -repository http://types.cs.washington.edu/checker-framework/eclipse/ -installIUs checker.framework.eclipse.feature.feature.group 

     #Downloads the workspace and extracts it
     sudo wget -nv "https://github.com/KahanPrabhu/ICSE-2011-Checker-Framework/raw/master/vm-content/workspace.tar.gz" -O /home/vagrant/workspace.tar.gz
     cd /home/vagrant && sudo tar -zxvf /home/vagrant/workspace.tar.gz
     

     #Downloads the files for the desktop from Github
     sudo wget -nv "https://raw.githubusercontent.com/KahanPrabhu/ICSE-2011-Checker-Framework/master/vm-content/Installation.txt" -O /home/vagrant/Desktop/Installation.txt

     sudo wget -nv "https://raw.githubusercontent.com/KahanPrabhu/ICSE-2011-Checker-Framework/master/vm-content/License.txt" -O /home/vagrant/Desktop/License.txt

     sudo wget -nv "https://raw.githubusercontent.com/KahanPrabhu/ICSE-2011-Checker-Framework/master/vm-content/Readme.txt" -O /home/vagrant/Desktop/Readme.txt

     sudo wget -nv "https://raw.githubusercontent.com/KahanPrabhu/ICSE-2011-Checker-Framework/master/vm-content/YoutubeDemoLink.desktop" -O /home/vagrant/Desktop/YoutubeDemoLink.
     sudo wget -nv "https://raw.githubusercontent.com/KahanPrabhu/ICSE-2011-Checker-Framework/master/vm-content/eclipse.desktop" -O /home/vagrant/Desktop/eclipse.desktop
     mkdir /home/vagrant/.config/autostart
     mv /home/vagrant/Desktop/eclipse.desktop /home/vagrant/.config/autostart

     sudo wget -nv "https://github.com/KahanPrabhu/ICSE-2011-Checker-Framework/tree/master/vm-content/Binaries" -O /home/vagrant/Desktop/Binaries 

     #Installs Adobe Flash Player for playing YouTube videos
     sudo apt-get install flashplugin-installer 

     #Removes all unnecessary applications
    sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
    sudo rm -f "/usr/share/applications/libreoffice-calc.desktop"
    sudo rm -f "/usr/share/applications/libreoffice-writer.desktop"
    sudo rm -f "/usr/share/applications/libreoffice-impress.desktop"
    sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"
    sudo rm -f "/usr/share/applications/unity-control-center.desktop"


    sudo reboot

  SHELL
end
